apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-study-scg-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-study-scg
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-study-scg
    spec:
      containers:
        - image: stringju/argo-test
          imagePullPolicy: Always
          name: hyunju-argocd-study-scg
          ports:
            - containerPort: 80
