apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stringju-argocd-study-scg
resources:
- namespace.yaml
- ../../base

images:
- name: stringju/argo-test
  newTag: adf37c5ce066a881c540078b1cc5de3df54d1ce0
